tunnel: d09e2876-986d-4dfc-9764-ff6f79da849b
credentials-file: /path/to/<d09e2876-986d-4dfc-9764-ff6f79da849b>.json

ingress:
  - hostname: bbr.trueth.kdns.fr
    service: http://localhost:8080
    originRequest:
      disableChunkedEncoding: true
  - service: http_status:404
