ingress:
  - hostname: bbr.trueth.kdns.fr
    service: http://localhost:8080
    originRequest:
      noTLSVerify: true
  - hostname: bbh.trueth.kdns.fr
    service: http://localhost:10002
    originRequest:
      http2Origin: true   # ← ဒါက အရေးကြီးဆုံး
  - service: http_status:404
