http_port 3128

# Xray HTTP inbound ကို upstream အနေနဲ့ သုံး
cache_peer 127.0.0.1 parent 1080 0 no-query default
never_direct allow all

# Cache မလိုဘူး
cache deny all

# Auth (မဖြစ်မနေ ထည့်ပါ)
auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwd
auth_param basic realm Proxy
acl authenticated proxy_auth REQUIRED

# Ports
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl Safe_ports port 8080
acl CONNECT method CONNECT

# Access
http_access allow authenticated
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access deny all

# DNS
dns_nameservers 8.8.8.8 1.1.1.1

# Hide
visible_hostname proxy
via off
forwarded_for delete
